### ISSUE TITLE
Deprecation warning in Elixir 1.5

### ISSUE THREAD

**Issue by woylie** [rhazdon/blue_bird#37]
Seems like we'll have to make a change for Elixir 1.5.

```
warning: passing GenEvent handlers (BlueBird.Formatter in this case) in the :formatters option of ExUnit is deprecated, please pass a GenServer instead. Check the documentation for the ExUnit.Formatter module for more information
  (ex_unit) lib/ex_unit/event_manager.ex:34: ExUnit.EventManager.add_handler/3
  (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
  (elixir) lib/enum.ex:675: Enum.each/2
  (ex_unit) lib/ex_unit/runner.ex:29: ExUnit.Runner.configure/1
  (ex_unit) lib/ex_unit/runner.ex:7: ExUnit.Runner.run/2
  (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
  (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
  (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by woylie** [comment]
fixed in PR #38
